### ISSUE TITLE
A coprocessor to sample keys

### ISSUE THREAD

**Issue by jkleckner** [tspannhw/hbasecoprocessor#1]
@tspannhw thank you for this nice example.  It looks like you inspired an [implementation of aggregation in the hbase-endpoint module](https://github.com/apache/hbase/blob/master/hbase-endpoint/src/main/java/org/apache/hadoop/hbase/client/coprocessor/AggregationClient.java).

I'm curious if you have run across a method to sample keys in order to find out what types of data are stored in a table?  Reasonable arguments would _start-key_, _end-key_, and _sample-fraction_.

Can you think of other ways to extract a key scheme?

**Comment by tspannhw** [comment]
This is a generic coprocessor, doing nothing special.

You can just use Phoenix and have a SQL table on top of them for optimum
